In [1]:
import pandas as pd

In [50]:
col_names = ["text", "label", "id"]
train = pd.read_csv("./data/go_emotion/full_dataset/train.tsv", sep="\t", names=col_names)

In [51]:
train

                                                    text label       id
0      My favourite food is anything I didn't have to...    27  eebbqej
1      Now if he does off himself, everyone will thin...    27  ed00q6i
2                         WHY THE FUCK IS BAYLESS ISOING     2  eezlygj
3                            To make her feel threatened    14  ed7ypvh
4                                 Dirty Southern Wankers     3  ed0bdzj
...                                                  ...   ...      ...
43405  Added you mate well I’ve just got the bow and ...    18  edsb738
43406  Always thought that was funny but is it a refe...     6  ee7fdou
43407  What are you talking about? Anything bad that ...     3  efgbhks
43408            More like a baptism, with sexy results!    13  ed1naf8
43409                                    Enjoy the ride!    17  eecwmbq

[43410 rows x 3 columns]

In [18]:
train["label"] = [labels.split(",") for labels in train["label"]]

In [20]:
train

                                                    text label       id
0      My favourite food is anything I didn't have to...  [27]  eebbqej
1      Now if he does off himself, everyone will thin...  [27]  ed00q6i
2                         WHY THE FUCK IS BAYLESS ISOING   [2]  eezlygj
3                            To make her feel threatened  [14]  ed7ypvh
4                                 Dirty Southern Wankers   [3]  ed0bdzj
...                                                  ...   ...      ...
43405  Added you mate well I’ve just got the bow and ...  [18]  edsb738
43406  Always thought that was funny but is it a refe...   [6]  ee7fdou
43407  What are you talking about? Anything bad that ...   [3]  efgbhks
43408            More like a baptism, with sexy results!  [13]  ed1naf8
43409                                    Enjoy the ride!  [17]  eecwmbq

[43410 rows x 3 columns]

In [21]:
train_exploded = train.explode('label')

In [22]:
train_exploded

                                                    text label       id
0      My favourite food is anything I didn't have to...    27  eebbqej
1      Now if he does off himself, everyone will thin...    27  ed00q6i
2                         WHY THE FUCK IS BAYLESS ISOING     2  eezlygj
3                            To make her feel threatened    14  ed7ypvh
4                                 Dirty Southern Wankers     3  ed0bdzj
...                                                  ...   ...      ...
43405  Added you mate well I’ve just got the bow and ...    18  edsb738
43406  Always thought that was funny but is it a refe...     6  ee7fdou
43407  What are you talking about? Anything bad that ...     3  efgbhks
43408            More like a baptism, with sexy results!    13  ed1naf8
43409                                    Enjoy the ride!    17  eecwmbq

[51103 rows x 3 columns]

In [27]:
train_exploded[train_exploded["label"] != '0']

                                                    text label       id
0      My favourite food is anything I didn't have to...    27  eebbqej
1      Now if he does off himself, everyone will thin...    27  ed00q6i
2                         WHY THE FUCK IS BAYLESS ISOING     2  eezlygj
3                            To make her feel threatened    14  ed7ypvh
4                                 Dirty Southern Wankers     3  ed0bdzj
...                                                  ...   ...      ...
43405  Added you mate well I’ve just got the bow and ...    18  edsb738
43406  Always thought that was funny but is it a refe...     6  ee7fdou
43407  What are you talking about? Anything bad that ...     3  efgbhks
43408            More like a baptism, with sexy results!    13  ed1naf8
43409                                    Enjoy the ride!    17  eecwmbq

[46973 rows x 3 columns]

In [68]:
def pre_processing(path):
    col_names = ["text", "label", "id"]
    df = pd.read_csv(path, sep="\t", names=col_names)
    
    # turn the labels into list
    df["label"] = [labels.split(",") for labels in df["label"]]

    # explod the dataframe
    df_exploded = df.explode('label')

    # change label data type
    df_exploded["label"] = df_exploded["label"].astype("int")
    
    # exclude the neutral emotion
    df_res = df_exploded[df_exploded["label"] != '0']

    return df_res

In [69]:
train = pre_processing("./data/go_emotion/full_dataset/train.tsv")

In [70]:
dev = pre_processing("./data/go_emotion/full_dataset/dev.tsv")

In [71]:
test = pre_processing("./data/go_emotion/full_dataset/test.tsv")

In [75]:
train.to_csv("./data/go_emotion/multi-label/train.csv", index=False)

In [76]:
dev.to_csv("./data/go_emotion/multi-label/valid.csv", index=False)

In [77]:
test.to_csv("./data/go_emotion/multi-label/test.csv", index=False)