In [190]:
import pandas as pd
import ast

In [203]:
col_names = ["text", "label", "id"]
train = pd.read_csv("./data/go_emotion/full_dataset/train.tsv", sep="\t", names=col_names)

In [204]:
train

                                                    text label       id
0      My favourite food is anything I didn't have to...    27  eebbqej
1      Now if he does off himself, everyone will thin...    27  ed00q6i
2                         WHY THE FUCK IS BAYLESS ISOING     2  eezlygj
3                            To make her feel threatened    14  ed7ypvh
4                                 Dirty Southern Wankers     3  ed0bdzj
...                                                  ...   ...      ...
43405  Added you mate well I’ve just got the bow and ...    18  edsb738
43406  Always thought that was funny but is it a refe...     6  ee7fdou
43407  What are you talking about? Anything bad that ...     3  efgbhks
43408            More like a baptism, with sexy results!    13  ed1naf8
43409                                    Enjoy the ride!    17  eecwmbq

[43410 rows x 3 columns]

In [205]:
train["label"].unique()

array(['27', '2', '14', '3', '26', '15', '8,20', '0', '6', '1,4', '5',
       '3,12', '6,22', '6,9,27', '12', '16,25', '2,7', '17', '25', '0,15',
       '15,18', '16,27', '7,13', '10', '20', '4', '13,15', '0,1', '13',
       '1', '0,5', '0,13,15', '9', '4,22', '24', '18', '7', '6,7', '22',
       '9,27', '4,5', '2,3', '0,8,15,17', '11', '7,15', '3,9,26', '13,18',
       '23', '1,27', '7,18', '10,22', '4,15', '0,26', '10,27', '1,26',
       '5,27', '8,27', '17,20', '10,20', '3,24', '2,27', '4,8', '3,27',
       '0,7', '8,18', '17,26', '3,9', '21', '18,27', '0,4', '4,7', '0,20',
       '16', '10,11', '0,1,17', '7,26', '14,26', '17,23', '24,25', '9,25',
       '3,22', '1,18', '1,5', '7,10', '0,18', '3,10', '7,25', '6,9',
       '3,18', '8', '0,27', '3,10,11', '3,6', '0,4,20', '0,25', '19',
       '15,17', '7,27', '25,27', '1,17', '4,17', '0,17', '0,4,26', '2,11',
       '22,27', '1,20', '13,26', '20,26', '15,27', '9,18', '1,25',
       '6,7,9,26', '6,22,27', '5,7', '4,27', '2,10', '2,9,25', '9,10,25',
       '13,17', '4,8,20,22', '1,22', '0,15,17', '1,10,18', '15,26',
       '15,25', '15,17,18', '9,11', '9,22', '2,3,9', '6,10', '1,3,8',
       '3,25', '0,6', '10,18', '4,6', '1,15', '4,17,20', '9,24',
       '7,24,25', '5,10', '0,10', '0,1,4', '5,24', '7,11', '0,15,18',
       '0,13', '7,12', '9,26', '4,20', '8,25', '9,17', '3,8', '6,7,27',
       '6,7,14', '2,9', '7,22', '0,23', '9,10', '14,19', '1,6', '11,25',
       '4,20,27', '4,10', '5,25', '3,4', '11,27', '15,24', '3,15', '5,20',
       '7,13,17', '11,14', '1,10', '20,27', '3,20', '5,22', '26,27',
       '6,8', '20,25', '0,8,15', '15,21', '12,27', '4,18', '0,17,20',
       '14,27', '3,9,27', '15,20', '14,22', '6,13', '4,11', '4,14',
       '22,25', '0,8', '17,27', '9,14', '0,9', '9,20', '9,19', '17,18',
       '22,26', '2,3,10', '19,22', '1,15,17', '18,26', '2,3,10,11',
       '0,14,26', '1,3', '15,22', '0,4,18', '7,20', '17,22', '0,4,5,17',
       '15,23', '10,19', '10,25', '6,26', '13,17,21', '9,20,25', '1,13',
       '0,22', '0,8,20', '8,9,20', '10,12', '3,11', '12,25', '6,27',
       '8,9', '13,27', '0,8,18', '2,11,12', '1,24', '6,7,22', '1,2',
       '2,11,27', '10,14', '6,18', '1,11', '4,25', '13,17,22', '0,21',
       '5,6', '5,18', '3,5', '9,10,27', '10,24', '1,7,15', '1,7',
       '4,15,23', '12,22', '1,20,24', '4,26', '5,8', '2,6', '6,15,26',
       '7,17', '23,27', '10,21', '1,12,20', '4,17,22', '13,22', '2,3,5',
       '2,9,11', '9,24,25', '14,18', '4,9', '21,27', '2,3,22', '0,15,26',
       '5,17', '4,23', '20,24', '8,14', '5,8,20', '8,15', '8,10',
       '7,10,17', '6,11', '5,9,25', '0,3', '2,20', '1,15,22', '4,21',
       '8,22', '6,15', '22,24', '6,15,22', '8,24', '11,20', '13,20',
       '5,15', '17,25', '16,19', '3,7,20', '0,10,15,22', '18,22', '18,24',
       '4,15,24', '0,15,27', '18,20', '3,13', '12,16', '2,3,27', '2,15',
       '11,15', '0,5,15', '1,9,22', '6,7,15', '2,25', '5,7,10', '16,26',
       '7,24', '13,17,18', '6,14', '0,18,25', '8,11', '0,14', '11,22',
       '5,13', '19,27', '3,17', '0,17,18', '5,14,19', '0,20,21', '7,9,26',
       '6,25', '2,22', '1,18,24', '13,23', '7,18,25', '0,6,27', '3,7',
       '10,15', '8,20,22', '10,26', '0,24', '13,17,18,26', '16,24,25',
       '14,25', '11,18', '3,9,25', '12,22,24', '2,3,11', '4,9,25,27',
       '19,25', '7,9', '20,22', '12,17', '2,23', '5,7,19', '6,24',
       '8,15,20', '4,18,20', '13,21', '9,12,14,19,25', '1,14', '2,5',
       '12,24', '2,4', '4,7,18', '11,24', '4,22,27', '0,6,10', '3,9,17',
       '18,19,25', '4,5,20', '5,23', '18,23', '13,17,20', '5,14', '8,13',
       '5,11,18', '7,10,11', '3,10,25', '9,22,25', '2,26', '2,3,4',
       '9,15', '2,3,24', '7,14', '1,8', '2,4,5', '7,14,22', '3,26',
       '3,6,7', '8,17', '2,3,15', '0,10,18', '0,13,18', '1,3,17',
       '1,15,20', '12,18', '3,11,25', '6,17', '0,3,4', '25,26', '3,14',
       '7,19', '14,22,25', '5,20,27', '1,3,10', '0,1,12', '6,17,18',
       '4,24', '8,11,18', '2,3,7', '5,26', '0,5,20', '12,14', '11,13',
       '0,18,22', '11,12', '0,1,13', '4,13', '0,6,7', '2,17', '0,4,22',
       '6,7,26', '0,4,13', '1,23', '11,19', '3,9,11', '0,1,7', '20,23',
       '5,7,20', '4,20,21', '24,27', '0,24,27', '20,24,25', '5,19',
       '4,13,26', '0,4,9', '3,8,20', '8,13,17', '1,9', '0,4,9,18',
       '0,4,15', '3,7,10', '7,11,25', '7,8', '1,2,3', '0,4,7,26',
       '5,20,25', '12,14,27', '0,2', '7,9,25', '5,15,23', '5,9,20',
       '20,21', '13,15,17', '6,12,25', '4,8,20', '2,18', '12,26', '6,7,9',
       '2,10,25', '5,25,27', '1,15,18', '18,25', '2,14', '3,21', '0,4,5',
       '3,4,7', '3,23', '5,18,27', '2,24', '17,21', '8,17,18', '4,18,27',
       '0,11,12', '4,20,22', '6,19', '1,10,27', '5,9', '6,7,10', '3,9,22',
       '3,10,12', '4,5,17', '4,17,27', '14,20', '9,10,24,25', '3,9,10',
       '2,10,15', '18,19', '1,7,20', '0,4,17,22', '15,18,20', '3,6,10',
       '10,23', '0,3,15', '1,12', '4,8,27', '14,17', '5,24,25', '7,15,20',
       '5,13,18,20', '4,19', '7,9,24,25', '7,10,25', '9,10,19', '5,16',
       '8,20,27', '0,11', '2,4,18', '22,26,27', '1,21', '24,26', '16,24',
       '1,11,20', '9,12', '0,4,17', '5,20,24', '1,3,22', '1,17,18',
       '18,20,27', '9,10,22', '18,20,25', '0,6,15', '1,4,10', '12,20',
       '3,6,25', '2,11,25', '9,15,22', '0,9,15', '13,15,17,20', '3,8,22',
       '3,14,25', '8,9,25', '0,6,7,15', '10,11,27', '9,13', '0,13,22',
       '0,9,18', '5,20,22', '5,15,18', '1,17,20', '3,15,23', '0,18,27',
       '0,5,18', '10,17,22', '14,24,25', '4,8,22', '0,13,17', '0,3,11',
       '4,13,20', '14,20,25', '13,22,26', '2,3,6', '11,14,20', '2,9,12',
       '0,15,20', '4,14,25', '0,14,25', '4,15,20', '1,10,15', '1,22,25',
       '1,13,17', '22,23', '5,15,17', '7,26,27', '2,12', '1,6,7',
       '15,20,24', '0,4,11,22', '9,12,22', '1,15,25', '17,24', '6,18,24',
       '2,10,11', '9,16', '1,13,26', '0,9,25', '10,13,17', '2,14,19',
       '0,4,11', '3,4,22', '0,4,24', '14,24', '0,7,13', '5,10,17',
       '1,6,7,17', '6,7,8', '4,9,22', '1,6,15', '7,10,27', '4,5,27',
       '4,22,24', '5,12,20', '10,17', '19,20', '6,20', '0,18,20',
       '9,14,20', '20,22,25', '2,18,27', '8,13,18', '3,15,20', '19,26',
       '8,10,20', '0,8,17', '7,23', '14,17,19', '9,17,18,25', '0,7,22',
       '11,17', '2,19', '6,12', '4,7,27', '3,10,27', '15,17,20', '4,5,18',
       '7,11,15', '5,8,22', '6,7,24', '14,19,27', '1,8,20', '0,14,19',
       '6,18,20', '6,23', '12,20,21', '15,16,25', '13,17,26', '11,17,23',
       '0,7,15', '3,19', '10,13', '2,3,12', '14,15', '4,12', '2,5,10',
       '1,17,27', '3,11,14', '8,18,20', '4,9,11', '3,6,14', '0,4,13,17',
       '0,3,9,18', '7,8,13', '2,9,10', '1,3,27', '7,18,26', '0,8,22',
       '1,14,19', '3,4,27', '9,12,25', '0,16', '0,13,26', '2,3,21',
       '2,3,26', '7,10,22', '0,21,26', '2,3,11,25', '15,24,25',
       '14,15,25', '0,5,15,18', '1,15,17,23', '5,16,25', '1,4,20',
       '13,24', '0,20,25', '7,15,26', '8,13,20', '1,6,17', '17,20,25',
       '3,9,24', '4,7,8', '10,20,25', '8,26', '2,8', '0,4,25', '9,25,27',
       '9,22,27', '5,11,20', '1,3,9', '7,20,26', '5,12', '0,1,11',
       '1,14,17', '5,9,10', '3,15,22', '3,4,20', '19,23', '0,15,22',
       '3,20,27', '3,7,27', '0,11,20', '5,7,15', '15,25,26', '8,16',
       '13,25', '6,10,18', '0,20,22', '3,9,16', '4,13,27', '1,19',
       '13,15,20', '3,7,11', '1,4,22', '9,10,11', '1,3,20', '3,16,25',
       '0,15,24,25', '0,10,13', '7,22,26', '1,6,26', '13,20,21',
       '5,14,27', '7,18,22', '0,12,13,26', '1,2,5,17', '13,14', '3,9,12',
       '0,1,18'], dtype=object)

In [206]:
train["label"] = [labels.split(",") for labels in train["label"]]
# train["label"] = train["label"].apply(ast.literal_eval)
# train["label"] = [label for label in train["label"] if len(label) > 1]
train_filtered = train[train['label'].str.len() > 1]

In [207]:
train

                                                    text label       id
0      My favourite food is anything I didn't have to...  [27]  eebbqej
1      Now if he does off himself, everyone will thin...  [27]  ed00q6i
2                         WHY THE FUCK IS BAYLESS ISOING   [2]  eezlygj
3                            To make her feel threatened  [14]  ed7ypvh
4                                 Dirty Southern Wankers   [3]  ed0bdzj
...                                                  ...   ...      ...
43405  Added you mate well I’ve just got the bow and ...  [18]  edsb738
43406  Always thought that was funny but is it a refe...   [6]  ee7fdou
43407  What are you talking about? Anything bad that ...   [3]  efgbhks
43408            More like a baptism, with sexy results!  [13]  ed1naf8
43409                                    Enjoy the ride!  [17]  eecwmbq

[43410 rows x 3 columns]

In [124]:
train_exploded = train_filtered.explode('label')

In [125]:
train_exploded

                                                    text label       id
7      We need more boards and to create a bit more s...     8  ef4qmod
7      We need more boards and to create a bit more s...    20  ef4qmod
11     Aww... she'll probably come around eventually,...     1  edex4ki
11     Aww... she'll probably come around eventually,...     4  edex4ki
15     Shit, I guess I accidentally bought a Pay-Per-...     3  edivtm3
...                                                  ...   ...      ...
43388  Fuck these trendy hipster joints. Give me my s...     3  ee3nyiy
43395  Sorry I kind of took it like you were flexing ...     1  eelhhzc
43395  Sorry I kind of took it like you were flexing ...    24  eelhhzc
43404  Your paranoia over it seems schizophrenic to m...     7  ef8ymm9
43404  Your paranoia over it seems schizophrenic to m...    27  ef8ymm9

[14795 rows x 3 columns]

In [27]:
train_exploded[train_exploded["label"] != '0']

                                                    text label       id
0      My favourite food is anything I didn't have to...    27  eebbqej
1      Now if he does off himself, everyone will thin...    27  ed00q6i
2                         WHY THE FUCK IS BAYLESS ISOING     2  eezlygj
3                            To make her feel threatened    14  ed7ypvh
4                                 Dirty Southern Wankers     3  ed0bdzj
...                                                  ...   ...      ...
43405  Added you mate well I’ve just got the bow and ...    18  edsb738
43406  Always thought that was funny but is it a refe...     6  ee7fdou
43407  What are you talking about? Anything bad that ...     3  efgbhks
43408            More like a baptism, with sexy results!    13  ed1naf8
43409                                    Enjoy the ride!    17  eecwmbq

[46973 rows x 3 columns]

In [264]:
def pre_processing(path):
    col_names = ["text", "label", "id"]
    df = pd.read_csv(path, sep="\t", names=col_names)
    
    # turn the labels into list
    df["label"] = [labels.split(",") for labels in df["label"]]

    df_filtered = df[df['label'].str.len() > 1]

    # explod the dataframe
    df_exploded = df_filtered.explode('label')

    # change label data type
    df_exploded["label"] = df_exploded["label"].astype("int")
    
    # exclude the neutral emotion
    df_res = df_exploded[df_exploded["label"] != 27]

    df_res["aug_text"] = df_res["text"]

    # df_res = df_res.drop_duplicates(subset='text', keep="first")

    return df_res[["text", "aug_text", "label"]]

In [265]:
train = pre_processing("./data/go_emotion/full_dataset/train.tsv")

/var/folders/0q/27zm2njj4yd26k5bldd_1_gr0000gn/T/ipykernel_49075/1239100950.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_res["aug_text"] = df_res["text"]

In [266]:
train["label"].unique()

array([ 8, 20,  1,  4,  3, 12,  6, 22,  9, 16, 25,  2,  7,  0, 15, 18, 13,
        5, 17, 26, 10, 24, 11, 14, 23, 19, 21])

In [267]:
train_orig[train_orig["label"] == 0]

,text,aug_text,label
5,damn youtube and outrage drama is super lucrat...,and the angry play is a super-profit re-examin...,0
18,famous for his 3-4 defense,he's famous for his 3-4 defense.,0
28,twilight... still a better love story than the...,dawn... is still a better love story than the ...,0
30,what a wonderful world,what a wonderful world.,0
44,you just make her sound awesome.,you just make her sound awesome.,0
...,...,...,...
23447,kirkland liquor is amazing. i can get a cheap ...,"i could buy a cheap bottle of vodka or scotch,...",0
23468,wow nice way to live in an echo chamber.,wow. that's a good way to live in the echo room.,0
23470,"even when it's bad, it's still pretty good","even if it's bad, it's not bad.",0
23471,this is my favorite reddit conversation i’ve s...,this is my favorite redacted conversation.,0
23474,"even though i didn't know you personally, but ...","i don't know you personally, but i just want t...",0

In [268]:
train.groupby("text").count().sort_values("aug_text")

                                                    aug_text  label
text
 "If you don't wear BROWN AND ORANGE...YOU DON'...         1      1
I feel like it's the 90s when everybody wanted ...         1      1
I feel like I’ve had this exact same conversati...         1      1
I fear it is already too late if he already use...         1      1
Tried to fight multiple times, cried, fallen ov...         1      1
...                                                      ...    ...
I do not, sorry! I am not talented in the ways ...         4      4
Happy birthday my guy! Hope you have a great da...         4      4
Utah roads are definitely some of the best out ...         4      4
Yeah I probably would've started crying on the ...         5      5
Thanks, I hate it.                                         6      6

[7098 rows x 2 columns]

In [269]:
dev = pre_processing("./data/go_emotion/full_dataset/dev.tsv")

/var/folders/0q/27zm2njj4yd26k5bldd_1_gr0000gn/T/ipykernel_49075/1239100950.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_res["aug_text"] = df_res["text"]

In [270]:
dev["label"].unique()

array([ 4, 12, 22,  1,  3, 25,  2, 10,  5,  7, 24,  0, 15,  6, 17, 11, 26,
       18, 13, 20,  9, 21,  8, 19, 14, 23, 16])

In [271]:
test = pre_processing("./data/go_emotion/full_dataset/test.tsv")

/var/folders/0q/27zm2njj4yd26k5bldd_1_gr0000gn/T/ipykernel_49075/1239100950.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_res["aug_text"] = df_res["text"]

In [272]:
train_orig = pd.read_csv("./data/go_emotion/train.csv")
val_orig = pd.read_csv("./data/go_emotion/valid.csv")
test_orig = pd.read_csv("./data/go_emotion/test.csv")

In [273]:
train_orig

,text,aug_text,label
0,why the fuck is bayless isoing,why the fuck is that,2
1,to make her feel threatened,makes her feel threatened.,14
2,dirty southern wankers,"the dirty, dirty southerners of the south.",3
3,omg peyton isn't good enough to help us in the...,december 2015 moon fan,26
4,yes i heard abt the f bombs! that has to be wh...,"thank you for the answer: ""until then, my husb...",15
...,...,...,...
23480,added you mate well i’ve just got the bow and ...,"i just got the bow, i like the game hunting si...",18
23481,always thought that was funny but is it a refe...,"it's always funny, but what do you mean",6
23482,what are you talking about? anything bad that ...,what are you talking about anything bad happen...,3
23483,"more like a baptism, with sexy results!","more like baptism, with sexy results!",13
23484,enjoy the ride!,enjoy the ride!,17

In [276]:
train = pd.concat([train_orig, train])

In [277]:
dev = pd.concat([val_orig, dev])

In [278]:
test = pd.concat([test_orig, test])

In [246]:
train.to_csv("./data/go_emotion/multi-label/train.csv",index=False)

In [247]:
dev.to_csv("./data/go_emotion/multi-label/valid.csv", index=False)

In [248]:
test.to_csv("./data/go_emotion/multi-label/test.csv", index=False)

In [279]:
train["label"].unique()

array([ 2, 14,  3, 26, 15,  0,  6,  5, 12, 17, 25, 10, 20,  4, 13,  1,  9,
       24, 18,  7, 22, 11, 23, 21, 16,  8, 19])

In [281]:
dev["label"].unique()

array([25, 20, 15,  2, 10, 18, 16,  9,  0,  3, 17, 14, 24,  1,  7,  8,  4,
       13,  6, 22, 23,  5, 11, 26, 21, 19, 12])

In [146]:
test["label"].uniq

,text,aug_text,label
10,[NAME] has towed the line of the Dark Side. He...,[NAME] has towed the line of the Dark Side. He...,3
10,[NAME] has towed the line of the Dark Side. He...,[NAME] has towed the line of the Dark Side. He...,10
11,Lol! But I love your last name though. XD,Lol! But I love your last name though. XD,1
11,Lol! But I love your last name though. XD,Lol! But I love your last name though. XD,18
13,"It's great that you're a recovering addict, th...","It's great that you're a recovering addict, th...",7
...,...,...,...
5414,"I know, right?! I was literally in tears Satur...","I know, right?! I was literally in tears Satur...",25
5415,"They are children, they have no souls.","They are children, they have no souls.",4
5415,"They are children, they have no souls.","They are children, they have no souls.",5
5419,My mom works for Nasa and apparently no. They ...,My mom works for Nasa and apparently no. They ...,1
5419,My mom works for Nasa and apparently no. They ...,My mom works for Nasa and apparently no. They ...,11

In [238]:
# pd.set_option('display.max_rows', None)
pd.reset_option('display.max_rows')

In [241]:
train[train['text'].str.contains(r'\(', regex=True)]

,text,aug_text,label
646,(It was a joke),(It was a joke),1
646,(It was a joke),(It was a joke),27
1114,Oh jeez I missed that :(,Oh jeez I missed that :(,9
1114,Oh jeez I missed that :(,Oh jeez I missed that :(,24
1327,Ah i wish i would’ve come across one! Just lef...,Ah i wish i would’ve come across one! Just lef...,8
...,...,...,...
43073,Fair enough! that's useful and relevant (if an...,Fair enough! that's useful and relevant (if an...,8
43073,Fair enough! that's useful and relevant (if an...,Fair enough! that's useful and relevant (if an...,20
43191,Good [NAME] ^(that's perfect),Good [NAME] ^(that's perfect),4
43333,Surely the error is lexical. And I think the o...,Surely the error is lexical. And I think the o...,10
43333,Surely the error is lexical. And I think the o...,Surely the error is lexical. And I think the o...,27

In [242]:
train_orig[train_orig['text'].str.contains(r'\(', regex=True)]

,text,aug_text,label
120,no he was given a bad team to work with unfort...,but he never got the last shot he deserved:,25
125,"at least you get sunny on netflix, they took i...",at least there's sunlight on the mesh fluorina...,25
128,my mom caught be masturbating to dominatrix po...,"my mother got caught masturbating, wanted to m...",1
137,"i live in suiderstrand, which is past aghulas,...","unfortunately, there's no fibre option here:",9
174,he probably banked on the inherent secrecy of ...,he may be betting on the secrecy inherent in t...,3
...,...,...,...
22987,[name]. hopefully that mindset will change (no...,i hope this attitude changes.,20
23050,podcasts also can help a lot to distract yours...,a podcast can also help distract itself.,4
23125,yes but that's largely changed in much of the ...,"surprisingly, one or two states have not legal...",26
23438,"that's not it, the game (sigil is a derivative...","no, it's not. it's a game, if it's a challenge...",15
23441,no it's propaganda we because r/politics only ...,"no, it's propaganda, because r/politics only p...",25

In [250]:
train.iloc[450:500]

,text,aug_text,label
1462,"Again, that + is going to make people not want...","Again, that + is going to make people not want...",10
1465,This is pretty worrying and makes me wonder wh...,This is pretty worrying and makes me wonder wh...,14
1465,This is pretty worrying and makes me wonder wh...,This is pretty worrying and makes me wonder wh...,19
1467,The dog has a very confused look on his face lol.,The dog has a very confused look on his face lol.,1
1467,The dog has a very confused look on his face lol.,The dog has a very confused look on his face lol.,6
1483,I believe [NAME] solved this issue back in 200...,I believe [NAME] solved this issue back in 200...,4
1483,I believe [NAME] solved this issue back in 200...,I believe [NAME] solved this issue back in 200...,27
1488,How will identity politics help this situation?,How will identity politics help this situation?,6
1488,How will identity politics help this situation?,How will identity politics help this situation?,7
1498,I’m gunna be the bigger man... blessings on yo...,I’m gunna be the bigger man... blessings on yo...,15
1498,I’m gunna be the bigger man... blessings on yo...,I’m gunna be the bigger man... blessings on yo...,27
1501,This is a depressing r/tworedditorsonecup,This is a depressing r/tworedditorsonecup,9
1501,This is a depressing r/tworedditorsonecup,This is a depressing r/tworedditorsonecup,25
1505,I agree with this. I'm extremely happy with th...,I agree with this. I'm extremely happy with th...,4
1505,I agree with this. I'm extremely happy with th...,I agree with this. I'm extremely happy with th...,17
1512,"At least he was polite - ""please"" fuck off!","At least he was polite - ""please"" fuck off!",2
1512,"At least he was polite - ""please"" fuck off!","At least he was polite - ""please"" fuck off!",3
1515,What song was that earlier ? It went oooh oooh...,What song was that earlier ? It went oooh oooh...,6
1515,What song was that earlier ? It went oooh oooh...,What song was that earlier ? It went oooh oooh...,7
1518,Yes! Wonder how tall the girls will end up 😂,Yes! Wonder how tall the girls will end up 😂,20
1518,Yes! Wonder how tall the girls will end up 😂,Yes! Wonder how tall the girls will end up 😂,26
1522,"This is simply honesty + humility. Indeed, ver...","This is simply honesty + humility. Indeed, ver...",4
1523,"Well, this is the first time I've seen that in...","Well, this is the first time I've seen that in...",13
1523,"Well, this is the first time I've seen that in...","Well, this is the first time I've seen that in...",26
1530,She’s a disgusting snob.. Feel bad for the wor...,She’s a disgusting snob.. Feel bad for the wor...,11
1530,She’s a disgusting snob.. Feel bad for the wor...,She’s a disgusting snob.. Feel bad for the wor...,25
1531,"If you want nuance, deep thought and construct...","If you want nuance, deep thought and construct...",10
1531,"If you want nuance, deep thought and construct...","If you want nuance, deep thought and construct...",20
1538,Pretty sure that had been upped to at least 10...,Pretty sure that had been upped to at least 10...,4
1538,Pretty sure that had been upped to at least 10...,Pretty sure that had been upped to at least 10...,20
1538,Pretty sure that had been upped to at least 10...,Pretty sure that had been upped to at least 10...,27
1545,You gotta find that fine line where you amass ...,You gotta find that fine line where you amass ...,5
1545,You gotta find that fine line where you amass ...,You gotta find that fine line where you amass ...,27
1554,180 is not good for checking enzyme deficiency...,180 is not good for checking enzyme deficiency...,10
1554,180 is not good for checking enzyme deficiency...,180 is not good for checking enzyme deficiency...,27
1559,Damn you and your facts.,Damn you and your facts.,2
1559,Damn you and your facts.,Damn you and your facts.,3
1566,IT'S ALL YOUR FAULT MAMA,IT'S ALL YOUR FAULT MAMA,9
1566,IT'S ALL YOUR FAULT MAMA,IT'S ALL YOUR FAULT MAMA,10
1573,Hey don't insult troglodytes like that. I'm su...,Hey don't insult troglodytes like that. I'm su...,4
1573,Hey don't insult troglodytes like that. I'm su...,Hey don't insult troglodytes like that. I'm su...,10
1585,I wish that was a thing 😅,I wish that was a thing 😅,8
1585,I wish that was a thing 😅,I wish that was a thing 😅,20
1589,"Probably. Sorry, OP. But don't worry. A lot of...","Probably. Sorry, OP. But don't worry. A lot of...",5
1589,"Probably. Sorry, OP. But don't worry. A lot of...","Probably. Sorry, OP. But don't worry. A lot of...",25
1591,"So is liking [NAME] enormous eyebrows ""biologi...","So is liking [NAME] enormous eyebrows ""biologi...",7
1594,I feel the same way! It just doesn’t get bette...,I feel the same way! It just doesn’t get bette...,3
1594,I feel the same way! It just doesn’t get bette...,I feel the same way! It just doesn’t get bette...,4
1601,I mean... this is some shit right here,I mean... this is some shit right here,11
1601,I mean... this is some shit right here,I mean... this is some shit right here,27